// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SignalR_Project1.Models;

[Table("Chat")]
public partial class Chat
{
    [Key]
    public int id { get; set; }

    [Unicode(false)]
    public string name { get; set; }

    [Unicode(false)]
    public string message { get; set; }
}