// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SignalR_Project1.Models;

public partial class ChatSignalRContext : DbContext
{
    public ChatSignalRContext()
    {
    }

    public ChatSignalRContext(DbContextOptions<ChatSignalRContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Chat> Chats { get; set; }



    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Chat>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK_M");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}